project:
  type: book

book:
  title: "That's weird! Anomaly&nbsp;detection using&nbsp;R"
  author:
    name: "<a href='https://robjhyndman.com'>Rob J Hyndman</a>"
    affiliation: "Monash University, Australia"
  site-url: "https://OTexts.com/weird"
  chapters:
    - index.qmd
    - "01-intro.qmd"
    - "02-univariate.qmd"
    - "03-multivariate.qmd"
    - "04-tests.qmd"
    - "05-boxplots.qmd"
    - "06-density.qmd"
    - "07-distance.qmd"
    - "08-highdim.qmd"
    - "09-timeseries.qmd"
    - "10-functional.qmd"
    - "11-network.qmd"
    - "12-imagevideo.qmd"
    - "13-text.qmd"
    - "14-distributions.qmd"
    - "15-cybersecurity.qmd"
    - "references.qmd"
  appendices:
    - "appendix.qmd"
  page-footer:
    left: "Published by OTexts using [Quarto](https://quarto.org). {{< fa regular copyright >}} [Rob J Hyndman](https://robjhyndman.com) []{#current-year}"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"
  favicon: favicon.ico

published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: weird.bib
biblio-style: authoryear-comp
fig-width: 8
fig-height: 5
fig-align: center
fig-dpi: 1200
output-width: 100%
highlight-style: tango

execute:
  freeze: auto
  collapse: true
  echo: true
  cache: true

format:
  html:
    theme:
      light:
        - cosmo
        - otexts.scss
    toc-title: "Sections"
    fontsize: 1rem
    linestretch: 1.5
    mainfont: "Noto Serif, Georgia, serif"
    html-math-method: katex
    code-link: false
    fig-responsive: true
    code-fold: true
    embed-resources: false
    include-in-header:
      - file: google_analytics.html
    include-after-body:
      - text: |
          <script>
            document.getElementById('current-year').textContent = new Date().getFullYear();
          </script>
